version: 0.2
phases:
    pre_build:
        commands:
            - echo Logging in to Amazon ECR...
            - $(aws ecr get-login --no-include-email --region sa-east-1)
    build:
        commands:
            - echo Building image...
            - docker build -t expressapi:latest .
            - echo Tagging image...
            - docker tag expressapi:latest 543454195198.dkr.ecr.sa-east-1.amazonaws.com/expressapi:latest
    post_build:
        commands:
            - echo Pushing image...
            - docker push 543454195198.dkr.ecr.sa-east-1.amazonaws.com/expressapi:latest
