version: 0.2

phases:
    install:
        runtime-versions:
            nodejs: 16
    pre_build:
        commands:
            - echo Install packages...
            - npm install
    build:
        commands:
            - echo Running tests...
            - npm run test
            - echo Create build...
            - npm run build:prod
    post_build:
        commands:
            - echo Removing unnecessary files...
            # - rm -rf node_modules/
            # - rm -rf src/
            # - rm -rf tests/
artifacts:
    base-directory: '.'
    files:
        - '**/*'
