version: '3.9'
services:
  redis:
    container_name: redis
    image: redis:latest
    ports:
      - '6379:6379'
      - '8001:8001'
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_HOST_AUTH_METHOD: password
    ports:
      - '5432:5432'
    restart: unless-stopped
